// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/port-adapters-arch/apps/control-plane/internal/application/edgeconfig"
)

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Render(ctx context.Context, in edgeconfig.RenderInput) (string, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconfig.RenderInput) (string, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconfig.RenderInput) string); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, edgeconfig.RenderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - in edgeconfig.RenderInput
func (_e *MockRenderer_Expecter) Render(ctx interface{}, in interface{}) *MockRenderer_Render_Call {
	return &MockRenderer_Render_Call{Call: _e.mock.On("Render", ctx, in)}
}

func (_c *MockRenderer_Render_Call) Run(run func(ctx context.Context, in edgeconfig.RenderInput)) *MockRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 edgeconfig.RenderInput
		if args[1] != nil {
			arg1 = args[1].(edgeconfig.RenderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenderer_Render_Call) Return(s string, err error) *MockRenderer_Render_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRenderer_Render_Call) RunAndReturn(run func(ctx context.Context, in edgeconfig.RenderInput) (string, error)) *MockRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
