// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/port-adapters-arch/apps/control-plane/internal/application/website"
	"github.com/tuannm99/port-adapters-arch/apps/control-plane/internal/domain/website"
)

// NewMockWebsiteUseCase creates a new instance of MockWebsiteUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsiteUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsiteUseCase {
	mock := &MockWebsiteUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebsiteUseCase is an autogenerated mock type for the WebsiteUseCase type
type MockWebsiteUseCase struct {
	mock.Mock
}

type MockWebsiteUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsiteUseCase) EXPECT() *MockWebsiteUseCase_Expecter {
	return &MockWebsiteUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWebsiteUseCase
func (_mock *MockWebsiteUseCase) Create(ctx context.Context, in websiteapp.CreateInput) (website.Website, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 website.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, websiteapp.CreateInput) (website.Website, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, websiteapp.CreateInput) website.Website); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(website.Website)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, websiteapp.CreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWebsiteUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in websiteapp.CreateInput
func (_e *MockWebsiteUseCase_Expecter) Create(ctx interface{}, in interface{}) *MockWebsiteUseCase_Create_Call {
	return &MockWebsiteUseCase_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockWebsiteUseCase_Create_Call) Run(run func(ctx context.Context, in websiteapp.CreateInput)) *MockWebsiteUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 websiteapp.CreateInput
		if args[1] != nil {
			arg1 = args[1].(websiteapp.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteUseCase_Create_Call) Return(website1 website.Website, err error) *MockWebsiteUseCase_Create_Call {
	_c.Call.Return(website1, err)
	return _c
}

func (_c *MockWebsiteUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, in websiteapp.CreateInput) (website.Website, error)) *MockWebsiteUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockWebsiteUseCase
func (_mock *MockWebsiteUseCase) GetByID(ctx context.Context, id string) (website.Website, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 website.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (website.Website, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) website.Website); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(website.Website)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteUseCase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWebsiteUseCase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWebsiteUseCase_Expecter) GetByID(ctx interface{}, id interface{}) *MockWebsiteUseCase_GetByID_Call {
	return &MockWebsiteUseCase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWebsiteUseCase_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockWebsiteUseCase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteUseCase_GetByID_Call) Return(website1 website.Website, err error) *MockWebsiteUseCase_GetByID_Call {
	_c.Call.Return(website1, err)
	return _c
}

func (_c *MockWebsiteUseCase_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (website.Website, error)) *MockWebsiteUseCase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWebsiteUseCase
func (_mock *MockWebsiteUseCase) List(ctx context.Context) ([]website.Website, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []website.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]website.Website, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []website.Website); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]website.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWebsiteUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebsiteUseCase_Expecter) List(ctx interface{}) *MockWebsiteUseCase_List_Call {
	return &MockWebsiteUseCase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWebsiteUseCase_List_Call) Run(run func(ctx context.Context)) *MockWebsiteUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsiteUseCase_List_Call) Return(websites []website.Website, err error) *MockWebsiteUseCase_List_Call {
	_c.Call.Return(websites, err)
	return _c
}

func (_c *MockWebsiteUseCase_List_Call) RunAndReturn(run func(ctx context.Context) ([]website.Website, error)) *MockWebsiteUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
